# Import Library

In [42]:
# for cleaning the dataset
import pandas as pd
import numpy as np

# for modeling the results
import seaborn as sns

# Cleaning the Dataset

In [43]:
#uploading dataset to file
csv_file_path = '/Users/kaitlynmcveigh/Documents/GitHub/DS480-Capstone/Weather2.csv'

weather = pd.read_csv(csv_file_path)
weather

,dt,dt_iso,timezone,city_name,lat,lon,temp,visibility,dew_point,feels_like,...,wind_gust,rain_1h,rain_3h,snow_1h,snow_3h,clouds_all,weather_id,weather_main,weather_description,weather_icon
0,1072915200,2004-01-01 00:00:00 +0000 UTC,-18000,New York,40.712775,-74.005973,278.05,NaN,271.79,274.34,...,NaN,NaN,NaN,NaN,NaN,0,800,Clear,sky is clear,01n
1,1072918800,2004-01-01 01:00:00 +0000 UTC,-18000,New York,40.712775,-74.005973,278.09,NaN,271.82,274.19,...,NaN,NaN,NaN,NaN,NaN,0,800,Clear,sky is clear,01n
2,1072922400,2004-01-01 02:00:00 +0000 UTC,-18000,New York,40.712775,-74.005973,278.32,10000.0,270.81,274.39,...,10.30,NaN,NaN,NaN,NaN,0,800,Clear,sky is clear,01n
3,1072926000,2004-01-01 03:00:00 +0000 UTC,-18000,New York,40.712775,-74.005973,277.48,NaN,271.68,273.34,...,NaN,NaN,NaN,NaN,NaN,2,800,Clear,sky is clear,01n
4,1072929600,2004-01-01 04:00:00 +0000 UTC,-18000,New York,40.712775,-74.005973,277.78,10000.0,270.36,274.50,...,NaN,NaN,NaN,NaN,NaN,0,800,Clear,sky is clear,01n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195188,1735671600,2024-12-31 19:00:00 +0000 UTC,-18000,New York,40.712775,-74.005973,283.96,10000.0,277.21,282.74,...,NaN,NaN,NaN,NaN,NaN,0,800,Clear,sky is clear,01d
195189,1735675200,2024-12-31 20:00:00 +0000 UTC,-18000,New York,40.712775,-74.005973,283.77,10000.0,277.90,282.64,...,5.36,NaN,NaN,NaN,NaN,0,800,Clear,sky is clear,01d
195190,1735678800,2024-12-31 21:00:00 +0000 UTC,-18000,New York,40.712775,-74.005973,283.26,10000.0,278.84,282.26,...,NaN,NaN,NaN,NaN,NaN,0,800,Clear,sky is clear,01d
195191,1735682400,2024-12-31 22:00:00 +0000 UTC,-18000,New York,40.712775,-74.005973,282.80,10000.0,278.59,280.45,...,NaN,NaN,NaN,NaN,NaN,0,800,Clear,sky is clear,01n
195192,1735686000,2024-12-31 23:00:00 +0000 UTC,-18000,New York,40.712775,-74.005973,282.38,10000.0,278.56,279.53,...,NaN,NaN,NaN,NaN,NaN,0,800,Clear,sky is clear,01n

In [44]:
#Converting dt_iso into DateTime Index
weather['dt_iso'] = weather['dt_iso'].str.replace(' UTC', '', regex=False)
weather['dt_iso'] = pd.to_datetime(weather['dt_iso'])

#setting dt_iso as index
weather = weather.set_index('dt_iso')

In [45]:
#Grouping only the numerical columns in the dataset to aggregate it from hourly to daily observations
weather = weather.groupby('dt_iso').mean(numeric_only=True)
weather = weather.resample('D').mean()

In [41]:
weather

,dt,timezone,lat,lon,temp (F),visibility,dew_point (F),feels_like (F),temp_min (F),temp_max (F),...,humidity,wind_speed,wind_deg,wind_gust,rain_1h,rain_3h,snow_1h,snow_3h,clouds_all,weather_id
dt_iso,,,,,,,,,,,,,,,,,,,,,
2004-01-01 00:00:00+00:00,1.072957e+09,-18000.0,40.712775,-74.005973,40.458333,10000.000000,27.000000,35.250000,39.750000,41.583333,...,57.125000,3.705417,215.333333,8.725000,NaN,NaN,NaN,NaN,12.166667,800.458333
2004-01-02 00:00:00+00:00,1.073043e+09,-18000.0,40.712775,-74.005973,39.375000,10000.000000,33.916667,37.625000,38.583333,40.458333,...,80.583333,1.476667,175.916667,NaN,0.155000,NaN,NaN,NaN,83.666667,778.166667
2004-01-03 00:00:00+00:00,1.073129e+09,-18000.0,40.712775,-74.005973,44.500000,10000.000000,42.041667,42.208333,43.291667,45.500000,...,91.041667,2.000417,152.500000,NaN,0.300000,NaN,NaN,NaN,84.541667,778.125000
2004-01-04 00:00:00+00:00,1.073216e+09,-18000.0,40.712775,-74.005973,48.000000,7520.000000,46.375000,45.625000,46.416667,49.250000,...,94.208333,2.612083,168.958333,7.700000,0.540000,0.65,NaN,NaN,96.250000,717.208333
2004-01-05 00:00:00+00:00,1.073302e+09,-18000.0,40.712775,-74.005973,38.583333,8116.666667,38.541667,32.541667,37.625000,39.875000,...,99.833333,3.991667,39.583333,8.620000,0.846000,2.05,NaN,NaN,100.000000,598.777778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27 00:00:00+00:00,1.735299e+09,-18000.0,40.712775,-74.005973,33.500000,10000.000000,25.000000,28.166667,31.791667,35.291667,...,68.416667,2.674583,141.083333,4.099048,NaN,NaN,NaN,NaN,3.500000,800.125000
2024-12-28 00:00:00+00:00,1.735385e+09,-18000.0,40.712775,-74.005973,42.708333,6152.045455,39.625000,40.291667,40.833333,44.208333,...,89.000000,1.883333,156.458333,2.583333,0.658000,1.65,NaN,NaN,89.583333,639.395833
2024-12-29 00:00:00+00:00,1.735472e+09,-18000.0,40.712775,-74.005973,49.625000,NaN,47.666667,48.583333,48.708333,50.958333,...,93.333333,1.975833,161.666667,1.624545,0.536923,NaN,NaN,NaN,98.541667,639.416667
2024-12-30 00:00:00+00:00,1.735558e+09,-18000.0,40.712775,-74.005973,54.833333,10000.000000,47.166667,53.583333,53.125000,56.041667,...,77.875000,4.472500,200.416667,8.045714,0.990909,NaN,NaN,NaN,70.833333,663.958333
2024-12-31 00:00:00+00:00,1.735645e+09,-18000.0,40.712775,-74.005973,48.291667,10000.000000,36.041667,45.291667,46.791667,49.625000,...,62.875000,3.188333,168.375000,4.558000,NaN,NaN,NaN,NaN,3.125000,800.125000

In [46]:
# Converting the values from C to F
weather['temp'] = ((weather['temp'] - 273.15) * 1.8) + 32

#Converts temp_max and temp_min to Fahrenheit
weather['temp_max'] = ((weather['temp_max'] - 273.15) * 1.8) + 32

weather['temp_min'] = ((weather['temp_min'] - 273.15) * 1.8) + 32

#Converts dew_point, and feels_like to Fahrenheit
weather['dew_point'] = ((weather['dew_point'] - 273.15) * 1.8) + 32

weather['feels_like'] = ((weather['feels_like'] - 273.15) * 1.8) + 32

#renames columns to reflect fahrenheit conversion
weather = weather.rename(columns={'temp': 'temp (F)',
                                  'dew_point': 'dew_point (F)',
                                  'feels_like': 'feels_like (F)',
                                  'temp_max': 'temp_max (F)',
                                  'temp_min': 'temp_min (F)'})

#make columns into whole numbers
weather['temp (F)'] = weather['temp (F)'].round(decimals=0)
weather['dew_point (F)'] = weather['dew_point (F)'].round(decimals=0)
weather['feels_like (F)'] = weather['feels_like (F)'].round(decimals=0)
weather['temp_max (F)'] = weather['temp_max (F)'].round(decimals=0)
weather['temp_min (F)'] = weather['temp_min (F)'].round(decimals=0)

In [48]:
#converting meters/sec into miles/hour (Imperial units)
weather['wind_speed'] = weather['wind_speed'] * 2.237
weather['wind_gust'] = weather['wind_gust'] * 2.237

#rename columns to reflect conversion
weather = weather.rename(columns={'wind_speed': 'wind_speed (mph)', 
                                  'wind_gust': 'wind_gust (mph)'})

weather['wind_gust (mph)'] = weather['wind_gust (mph)'].round(decimals=0)
weather['wind_speed (mph)'] = weather['wind_speed (mph)'].round(decimals=0)

In [49]:
#Convert mm to inches
weather['rain_1h'] = weather['rain_1h'] / 25.4
weather['rain_3h'] = weather['rain_3h'] / 25.4
weather['snow_1h'] = weather['snow_1h'] / 25.4
weather['snow_3h'] = weather['snow_3h'] / 25.4

#rename columns to reflect conversion
weather = weather.rename(columns={'rain_1h': 'rain_1h (in)',
                                  'rain_3h': 'rain_3h (in)',
                                  'snow_1h': 'snow_1h (in)',
                                  'snow_3h': 'snow_3h (in)'})

In [50]:
#Convert km to statute miles (SM)
weather['visibility'] = weather['visibility'] / 1.609

weather = weather.rename(columns={'visibility': 'visibility (SM)'})

In [27]:
#Cleaning the remainder of the dataset

In [51]:
#seeing if there are any values in this column
unique_values = weather['sea_level'].unique()
print(unique_values)

unique_values = weather['grnd_level'].unique()
print(unique_values)

[nan]
[nan]

In [52]:
#removing columns that are not needed
weather = weather.drop(['lat', 'lon', 'dt', 'timezone', 'sea_level', 'grnd_level','weather_id'], axis = 1)

#removed lat, long, city_name, and timezone because they are all the same for each observation since this is data for the same city
#removed dt because it was not useful to the dataset
#removed sea_level and grnd_level because there were no values in the columns, all NaN

In [53]:
#adding units to column heads

weather = weather.rename(columns={'pressure': 'pressure (hPa)', 
                                  'humidity': 'humidity (%)',
                                  'clouds_all': 'cloudiness (%)',})

In [54]:
#updated column descriptions
column_descriptions = {
    'dt_iso': 'Date and time',
    'temp (F)': 'Temperature in Fahrenheit',
    'visibility (SM)': 'Average visibility, Units: statute miles (SM). The maximum value of the visibility is 6.2 SM',
    'dew_point (F)': 'Atmospheric temperature (varying according to pressure and humidity) below which water droplets begin to condense and dew can form',
    'feels_like (F)': 'Temperature parameter that accounts for the human perception of weather',
    'temp_min (F)': 'Minimum temperature at the moment. (use these parameter optionally).',
    'temp_max (F)': 'Same as temp_min',
    'pressure (hPa)': 'Atmospheric pressure (on the sea level), Units: hPa',
    'humidity (%)': 'Humidity percentage',
    'wind_speed (mph)': 'Units: miles/hour',
    'wind_deg': 'Wind direction, Units: degrees',
    'wind_gust (mph)': 'Units: miles/hour',
    'rain_1h (in)': 'Rain volume for the last hour, Units: inches',
    'rain_3h (in)': 'Rain volume for the last 3 hours, Units: inches',
    'snow_1h (in)': 'same as rain but measured in liquid state.',
    'snow_3h (in)': 'same as rain but measured in liquid state.',
    'cloudiness (%)': 'cloudiness percentage',
    }

In [55]:
weather

,temp (F),visibility (SM),dew_point (F),feels_like (F),temp_min (F),temp_max (F),pressure (hPa),humidity (%),wind_speed (mph),wind_deg,wind_gust (mph),rain_1h (in),rain_3h (in),snow_1h (in),snow_3h (in),cloudiness (%)
dt_iso,,,,,,,,,,,,,,,,
2004-01-01 00:00:00+00:00,40.0,6215.040398,27.0,35.0,40.0,42.0,1023.541667,57.125000,8.0,215.333333,20.0,NaN,NaN,NaN,NaN,12.166667
2004-01-02 00:00:00+00:00,39.0,6215.040398,34.0,38.0,39.0,41.0,1023.666667,80.583333,3.0,175.916667,NaN,0.006102,NaN,NaN,NaN,83.666667
2004-01-03 00:00:00+00:00,45.0,6215.040398,42.0,42.0,43.0,46.0,1016.958333,91.041667,4.0,152.500000,NaN,0.011811,NaN,NaN,NaN,84.541667
2004-01-04 00:00:00+00:00,48.0,4673.710379,46.0,46.0,46.0,49.0,1013.333333,94.208333,6.0,168.958333,17.0,0.021260,0.025591,NaN,NaN,96.250000
2004-01-05 00:00:00+00:00,39.0,5044.541123,39.0,33.0,38.0,40.0,1012.666667,99.833333,9.0,39.583333,19.0,0.033307,0.080709,NaN,NaN,100.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27 00:00:00+00:00,33.0,6215.040398,25.0,28.0,32.0,35.0,1031.333333,68.416667,6.0,141.083333,9.0,NaN,NaN,NaN,NaN,3.500000
2024-12-28 00:00:00+00:00,43.0,3823.521103,40.0,40.0,41.0,44.0,1026.208333,89.000000,4.0,156.458333,6.0,0.025906,0.064961,NaN,NaN,89.583333
2024-12-29 00:00:00+00:00,50.0,NaN,48.0,49.0,49.0,51.0,1020.375000,93.333333,4.0,161.666667,4.0,0.021139,NaN,NaN,NaN,98.541667
2024-12-30 00:00:00+00:00,55.0,6215.040398,47.0,54.0,53.0,56.0,1005.208333,77.875000,10.0,200.416667,18.0,0.039012,NaN,NaN,NaN,70.833333
2024-12-31 00:00:00+00:00,48.0,6215.040398,36.0,45.0,47.0,50.0,1011.125000,62.875000,7.0,168.375000,10.0,NaN,NaN,NaN,NaN,3.125000

# Visualizations

In [ ]:
#Start off with visualizations that expand our knowledge of the dataset and its variables
#heat plots, correlation maps, etc.